name: CI
#
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
#  push:
#    branches: [ master ]
jobs: 
  linux: 
    name: "Backported nb-javac"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
            distribution: 'zulu'
            java-version: 8
      - name: Record JDK8
        run: echo "$JAVA_HOME" | tee jdk8
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            distribution: 'zulu'
            java-version: 17.0.0+35-ea
      - name: Do build
        run: JAVA_HOME8=`cat jdk8` JAVA_HOME17=$JAVA_HOME bash build.sh
